name: wizarding_world
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+2

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.4.2+1
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  very_good_analysis: ^5.1.0
  equatable: ^2.0.5
  faker: ^2.1.0
  retrofit: ^4.1.0
  logger: ^2.2.0
  mockito: ^5.4.4
  flutter_bloc: ^8.1.5
  bloc: ^8.1.4
  get_it: ^7.6.7
  device_preview: ^1.1.0
  responsive_builder: ^0.7.0
  auto_route: ^8.0.3
  auto_route_generator: ^8.0.0
  flutter_snake_navigationbar: ^0.6.1
  shared_preferences: ^2.2.2
  change_case: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  test: ^1.24.9
  retrofit_generator: ^8.1.0

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Kanit
      fonts:
        - asset: assets/fonts/Kanit/Kanit-Black.ttf
        - asset: assets/fonts/Kanit/Kanit-BlackItalic.ttf
        - asset: assets/fonts/Kanit/Kanit-Bold.ttf
        - asset: assets/fonts/Kanit/Kanit-BoldItalic.ttf
        - asset: assets/fonts/Kanit/Kanit-ExtraBold.ttf
        - asset: assets/fonts/Kanit/Kanit-ExtraBoldItalic.ttf
        - asset: assets/fonts/Kanit/Kanit-ExtraLight.ttf
        - asset: assets/fonts/Kanit/Kanit-ExtraLightItalic.ttf
        - asset: assets/fonts/Kanit/Kanit-Italic.ttf
        - asset: assets/fonts/Kanit/Kanit-Light.ttf
        - asset: assets/fonts/Kanit/Kanit-LightItalic.ttf
        - asset: assets/fonts/Kanit/Kanit-Medium.ttf
        - asset: assets/fonts/Kanit/Kanit-MediumItalic.ttf
        - asset: assets/fonts/Kanit/Kanit-Regular.ttf
        - asset: assets/fonts/Kanit/Kanit-SemiBold.ttf          
        - asset: assets/fonts/Kanit/Kanit-SemiBoldItalic.ttf
        - asset: assets/fonts/Kanit/Kanit-Thin.ttf
        - asset: assets/fonts/Kanit/Kanit-ThinItalic.ttf
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Light.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand/Quicksand-SemiBold.ttf